version: "3.9"

networks:
  net:

services:
  flaskapi:
    build:
      context: .
      dockerfile: ../v5/Dockerfile
    image: flask-api
    pull_policy: missing
    restart: always
    container_name: flaskapi
    command: gunicorn --reload --bind 0.0.0.0:8000 app:app
    ports:
      - ${FLASK_PORT:-8000}:8000
    env_file:
      - .env
    volumes:
      - ./web:/web
