version: "3.9"


services:
  flaskapi:
    build: .
    image: flask-api
    restart: always
    container_name: flaskapi
    command: /home/.env/bin/gunicorn --reload --bind 0.0.0.0:8000 app:app
    healthcheck:
      test: "curl -kfsS http://127.0.0.1:8000/healthcheck | grep UP | wc -l"
      timeout: 10s
      retries: 5
    ports:
      - ${FLASK_PORT:-8000}:8000
    env_file:
      - .env
    volumes:
      - ./web:/home/web
