version: "3.9"

networks:
  net:

services:
  ids:
    build:
      context: .
      dockerfile: Dockerfile
    image: trained-model

    # (for CI)
    # pull_policy: if_not_present
    pull_policy: missing
    restart: always
    container_name: cds
    command: sh -c "./onboot.sh app"
    env_file:
      - .env
    volumes:
      - ./web:/web
