version: "3.9"

networks:
  net:

services:
  if_app_haproxy:
    image: haproxy:2.9.7-bookworm
    restart: always
    container_name: cf_app_haproxy
    ports:
      - ${WEB:-8100}:80
      - ${DASHBOARD:-8200}:8404
    env_file:
      - .env
    volumes:
      - ./:/usr/local/etc/haproxy:ro
    networks:
      - net

  if_haproxy_web1:
    image: jmalloc/echo-server
    restart: always
    container_name: cf_haproxy_web1
    networks:
      - net

  if_haproxy_web2:
    image: jmalloc/echo-server
    restart: always
    container_name: cf_haproxy_web2
    networks:
      - net
