services:
  if_haproxy_web1:  &if_haproxy_web1
    image: python:3.12.0-slim-bookworm
    command: python3 share_global.py
    working_dir: /web
    volumes:
      - ./ancillaries:/web
    networks:
      - net

  if_haproxy_web2:
    <<: *if_haproxy_web1
    restart: always
    command: python3 share_global.py
    working_dir: /web
    volumes:
      - ./ancillaries:/web
    networks:
      - net

networks:
  net:
