version: "3.9"

networks:
  net:

services:
  haproxy-if-web1:
    image: python:3.12.0-slim-bookworm
    restart: always
    command: python3 share_global.py
    volumes:
      - ./web/ancillaries:/web
    working_dir: /web
    networks:
      - net

  haproxy-if-web2:
    image: python:3.12.0-slim-bookworm
    restart: always
    command: python3 share_global.py
    volumes:
      - ./web/ancillaries:/web
    working_dir: /web
    networks:
      - net
